name: Hadolint Dockerfile scan

on: [pull_request]

permissions:
  contents: read

jobs:
  hadolint:
    name: Run Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: devops/docker/deb/Dockerfile.debian13
