name: semgrep Security Scan

on:
  pull_request:
    paths:
      - "main.go"

permissions:
  contents: read

jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: '3.13'
    - name: Install semgrep cli
      run: |
        python3 -m pip install semgrep
        semgrep --version


      # TODO: bump action
      # - name: Semgrep SAST Scan
      #   with:
      #     # Несколько наборов правил
      #     config: |
      #       p/c
      #       p/security-audit
      #       p/owasp-top-ten
      #       p/golang
      #       p/cwe-top-25
