name: semgrep Security Scan

on:
  pull_request:
    paths:
      - "main.go"

permissions:
  contents: read

jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: '3.13'
    - name: Install semgrep cli
      run: |
        python3 -m pip install semgrep
        semgrep --version

    - name: Semgrep SAST Scan
      run: |
        semgrep scan --config p/c --config p/security-audit --config p/owasp-top-ten --config p/golang --config p/cwe-top-25 .
