name: tests-go

on:
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run tests
        run: |
          make test
