name: Trivy Scan

on:
  pull_request:
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - 'devops/docker/deb/**'

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner on filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs" # Scan the file system
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
